ci: switch to git clone of umoci
go get has been showing a *lot* of intermittent failures in ci with:

Cloning into 'umoci'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: expected flush after ref listing

Turns out this does not fix it.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>